### ISSUE TITLE
NullReferenceException error when trying to use in Middleware

### ISSUE THREAD

**Issue by crittag** [wangkanai/Detection#103]
I think this is similar to #83 but there was no detail of the resolution there.

I am trying to use Detection in Middleware which gets files from data and writes them to the Response. Detection is being used to correctly generate the Content-Disposition header to get it right for different browsers/platforms.

My middleware is:
`public class ImageHandlerMiddleware
  {
    private readonly RequestDelegate _next;
    private readonly IMediaService _mediaService;
    private readonly IBrowserResolver _browserResolver;
    private readonly IPlatformResolver _platformResolver;
    private readonly IImageProcessorService _imageProcessor;

    public ImageHandlerMiddleware(
        RequestDelegate next
        , IMediaService mediaService
        , IBrowserResolver browserResolver
        , IPlatformResolver platformResolver
        , IImageProcessorService imageProcessor
      )
    {
      _next = next;
      _mediaService = mediaService;
      _browserResolver = browserResolver;
      _platformResolver = platformResolver;
      _imageProcessor = imageProcessor;
    }

    public async Task Invoke( HttpContext context )
    {
      var pathSegments = context.Request.Path.ToSegments();

      var width = context.Request.Query[ "w" ].FirstOrDefault()?.ToInt32();
      var height = context.Request.Query[ "h" ].FirstOrDefault()?.ToInt32();

      var media = await _mediaService.GetMediaAsync( pathSegments.Last() );

      if ( media != null )
      {
        if ( width != null || height != null )
        {
          media.FileData = _imageProcessor.Resize( media.FileData, width, height );
        }
      }
      else
      {

        // TODO: get standard missing image graphic
      }

            context.Response.Clear();
            context.Response.ContentType = media.MimeType;
            context.Response.Headers.Add( HeaderNames.CacheControl, "no-store,no-cache" );
            context.Response.Headers.Add( HeaderNames.Pragma, "no-cache" );
            context.Response.Headers.Add(
                HeaderNames.ContentDisposition,
                media.FileName.ToInlineHeader(
                    _browserResolver, _platformResolver, media.FileExtension
                  )
              );
            await context.Response.Body.WriteAsync( media.FileData, 0, media.FileData.Length );
    }

  }`

This is being mapped using:

`app.MapWhen(
            context => context.Request.Path.StartsWithSegments( "/image" ),
            imageApp =>
            {
              imageApp.UseMiddleware<ImageHandlerMiddleware>();
            }
          );`

The full error message is:

Stopped program because of exception System.ArgumentNullException: Value cannot be null.
Parameter name: Context
   at Wangkanai.Detection.UserAgentService.CreateUserAgent(HttpContext context)
   at Wangkanai.Detection.UserAgentService..ctor(IServiceProvider services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.MapWhenExtensions.MapWhen(IApplicationBuilder app, Func`2 predicate, Action`1 configuration)
   at D*****.Module.Core.Middleware.ImageHandlerMiddlewareExtensions.UseImageHandler(IApplicationBuilder app) in D:\_Websites\D*****\D*****_core\D*****\src\Modules\D*****.Module.Core\Middleware\ImageHandlerMiddlewareExtensions.cs:line 17
   at D*****.Module.Core.ModuleInitializer.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\_Websites\D*****\D*****_core\D*****\src\Modules\D*****.Module.Core\ModuleInitializer.cs:line 31
   at D*****.WebHost.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\_Websites\D*****\D*****_core\D*****\src\D*****.WebHost\Startup.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at D*****.WebHost.Program.Main(String[] args) in D:\_Websites\D*****\D*****_core\D*****\src\D*****.WebHost\Program.cs:line 22

I have tried the FixDetectionMiddleware on suggested in #73 but that hasn't fixed the issue.

Any further assistance would be welcome

Cheers
Greg

**Comment by wangkanai** [comment]
I think you middleware should be above the `UseMVC()` and above `UseDetection()`.
See if that help for me please.

![image](https://user-images.githubusercontent.com/10666633/57061356-bd8e2c80-6ce6-11e9-8997-4f25f7cf433e.png)

**Comment by wangkanai** [comment]
fixed with pr #126
