### ISSUE TITLE
Error in Blazor Server

### ISSUE THREAD

**Issue by BobBonser** [wangkanai/Detection#442]
I am getting an error after publishing a Blazor Server app to my server. The app runs fine when I run in Kestrel locally when developing but hapens after I publish the app.

System.UserAgentServiceArgumentNullException: Value cannot be null. (Parameter 'Context')
   at Wangkanai.Detection.UserAgentService.CreateUserAgent(HttpContext context)
   at Wangkanai.Detection.UserAgentService..ctor(IServiceProvider services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by wangkanai** [comment]
Which version of detection are you using there?

**Comment by BobBonser** [comment]
I am using 2.0.1.
Thanks.

**Comment by wangkanai** [comment]
Oh, now I understand why you have this error. Because 2.0 doesn't have UserAgent skipping.
Try upgrade to 3.0 alpha 12

**Comment by BobBonser** [comment]
I upgraded to 3.0 alpha 12 and I am still getting the error.
It is very strange that the error only happens after I publish the app and not when I am debugging locally.

**Comment by wangkanai** [comment]
Very interesting! Does the server produce the same error after you have upgraded to 3.0 alpha 12 comparing to the first post above in this issue?

**Comment by BobBonser** [comment]
Yes

**Comment by wangkanai** [comment]
Can you help me reproduce the issue on an github repo, i would like to investigate more in detail. Or we can have a remote session for me to see the issue as is.

**Comment by BobBonser** [comment]
I don't think I can do a review session as this is on our server at work
and I'm not sure the firewall will allow it.

I will try to reproduce it locally and let you know.

**Comment by wangkanai** [comment]
I think that I found the root cause your issue. Examining the code, I feel the propose of the code is clear by design. While in your case because its Blazar app running emulating the client browser on the server and transmitting the render view to the client via WebSocket. 

The only fixed that I can see at the current time being is have a hack built into the `UserAgentService` to not throw null exception. Which is not a good principle to do, I would have a hack out with 3.0-alpha13 first. Then i would evaluate the matter later day.

**Comment by wangkanai** [comment]
I hope that 3.0-alpha13 release solve your issue.

Please give me a heads up of how did it go too.

Thank you mate.

**Comment by BobBonser** [comment]
Sorry for the late reply.  I get a new error now.
[image: image.png]

**Comment by wangkanai** [comment]
@BobBonser nothing is showing in your image

**Comment by BobBonser** [comment]
[image: newError.png]
I guess email pictures don't come through.

**Comment by BobBonser** [comment]
I guess E-Mail pictures don't come through.
Try viewing the picture here.

https://drive.google.com/file/d/16z7lf9HD2381VVKf5qWW4en7S-lRPXau/view?usp=sharing

**Comment by wangkanai** [comment]
The access is denied from your google drive link

![image](https://user-images.githubusercontent.com/10666633/96390690-05a55580-11e0-11eb-80d2-12b5826780f2.png)

**Comment by BobBonser** [comment]
You should have access now.

**Comment by wangkanai** [comment]
Got it, thank you mate. I will have a look at the error.

**Comment by wangkanai** [comment]
Reference to PR #457 I have working concept with Detection in Blazor Server Side App.

![image](https://user-images.githubusercontent.com/10666633/96408333-73b44180-120d-11eb-9a78-932002d4b768.png)

**Comment by wangkanai** [comment]
@BobBonser Please see how does [3.0-alpha14](https://www.nuget.org/packages/Wangkanai.Detection/3.0.0-alpha14) work out for you. I did a few [improvements](https://github.com/wangkanai/Detection/releases/tag/3.0-Alpha14) to the code base for exception handle.

**Comment by BobBonser** [comment]
It is working now!  Thanks.

**Comment by wangkanai** [comment]
Your welcome Bob 😃
