### ISSUE TITLE
System.InvalidOperationException on Program.Main Method-  Release 3.0

### ISSUE THREAD

**Issue by manduriomane** [wangkanai/Detection#478]
### Describe the bug
Hi,
I have updated Detection from 3.0.0 beta 1 version to 3.0 version and now I have a problem.

**Main** method of **Program** class of my webapi throw an exception while it try to execute
`webHost.Run()`

This is the exception

```
[System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Microsoft.AspNetCore.Session.ISessionStore' while attempting to activate 'Microsoft.AspNetCore.Session.SessionMiddleware'.
  Source=Microsoft.AspNetCore.Http.Abstractions
  StackTrace:
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.UseWhenExtensions.<>c__DisplayClass0_0.<UseWhen>b__0(RequestDelegate main)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at VM2WebAPI.Program.Main(String[] args) in C:\Progetti\VSTS\Villaggio Musicale\WebAPI\VM2WebAPI\VM2WebAPI\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]
    VM2WebAPI.Program.Main(string[]) in Program.cs
](url)
```
![detection-error](https://user-images.githubusercontent.com/25469100/104481149-b8aa0300-55c5-11eb-9f10-90a5bbd9f301.JPG)

Up to version 3.0.0 beta 1 all works fine.

How I can fix it?

Thanks

**Comment by felipejunges** [comment]
It now required you to configure Session to use Wangkanai:

**On Startup.cs, ConfigureServices():**
```
services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromSeconds(10);
    options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
});
```

**On Configure():**
`app.UseSession();`

**Comment by manduriomane** [comment]
Thanks Felipe

**Comment by wangkanai** [comment]
@manduriomane Thank you for help there

**Comment by dnxit** [comment]
Hi

It would be great if you can update it on the main page https://github.com/wangkanai/Detection, it took me 3 hours to understand which service started using Session after I migrated from .Net 3.1 to 5.0. It may save someone else some time 

Thanks

**Comment by wangkanai** [comment]
@dnxit thank you for recommendations and @felipejunges for the update in documentation.
