### ISSUE TITLE
NullReferenceException error in debug output

### ISSUE THREAD

**Issue by YZahringer** [wangkanai/Detection#76]
I have a NullReferenceException error when I inject `IBrowserResolver` into a `Middleware`. Not on all queries.

````cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseDeveloperExceptionPage();
    app.UseMiddleware<SimpleMiddleware>();
}

internal class SimpleMiddleware
{
    private readonly RequestDelegate _next;

    public SimpleMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public Task InvokeAsync(HttpContext context, IBrowserResolver browserResolver)
    {
        return _next(context);
    }
}
````
Exception:
`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wangkanai.Detection.Collections.InternetExplorer..ctor(String agent)
   at Wangkanai.Detection.BrowserResolver.GetBrowser()
   at Wangkanai.Detection.BrowserResolver..ctor(IUserAgentService service)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)
   at lambda_method(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by YZahringer** [comment]
I think is same issue https://github.com/wangkanai/Detection/issues/73

**Comment by YZahringer** [comment]
When did you plan to release a beta9?

**Comment by wangkanai** [comment]
@YZahringer let me clear up my time maybe July or August to get beta 9 rollout

**Comment by YZahringer** [comment]
Any news?

**Comment by wangkanai** [comment]
@YZahringer could you please help me answer the question in #85 to make a valid argument before i close the pull request.

Thank you.
