### ISSUE TITLE
Browser version parser fails

### ISSUE THREAD

**Issue by yuri-martynov** [wangkanai/Detection#89]
System.ArgumentException: Version string portion was too short or too long.
Parameter name: input
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Wangkanai.Detection.Collections.Safari..ctor(String agent)
   at Wangkanai.Detection.BrowserResolver.GetBrowser()
   at Wangkanai.Detection.BrowserResolver..ctor(IUserAgentService service)

**Comment by wangkanai** [comment]
Look like migrating to Systwm.Version was not a good idea. #77 

We will need to review this in next release beta10, I the meantime you can down grade to beta8.

**Comment by SamKO91** [comment]
@wangkanai I just came across this one as well.

Errror:
_System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Wangkanai.Detection.Collections.Safari..ctor(String agent)
   at Wangkanai.Detection.BrowserResolver.GetBrowser()
   at lambda_method(Closure , ServiceProviderEngineScope )_

User-Agent: **Mozilla/5.0 (BB10; Touch) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.0.9.2372 Mobile Safari/537.10+**

Issue is the "+" at the end of the string

Issue was discovered by using Chrome Dev Tools and selecting BlackBerry Z30 from the Devices List to preview website for that device.

**Comment by wangkanai** [comment]
fixed with pr #128
